export const ingredients = [
  "Maida flour",
  "yogurt",
  "oil",
  "sugar",
  "Gram flour",
  "ghee",
  "Carrots",
  "milk",
  "cashews",
  "raisins",
  "Flour",
  "kewra",
  "clarified butter",
  "almonds",
  "pistachio",
  "saffron",
  "green cardamom",
  "Milk powder",
  "plain flour",
  "baking powder",
  "water",
  "rose water",
  "Sugar syrup",
  "lentil flour",
  "Maida",
  "corn flour",
  "baking soda",
  "vinegar",
  "curd",
  "turmeric",
  "Cashews",
  "Milk",
  "cottage cheese",
  "rice",
  "dried fruits",
  "nuts",
  "Yogurt",
  "besan",
  "powdered sugar",
  "yoghurt",
  "Firm white pumpkin",
  "kitchen lime",
  "alum powder",
  "Condensed milk",
  "spices",
  "Semolina",
  "Khoa",
  "coconut",
  "molu leaf",
  "dry fruits",
  "Chhena",
  "cream",
  "Yoghurt",
  "fennel seeds",
  "Besan flour",
  "jaggery",
  "Rice flour",
  "wheat flour",
  "sweetened milk",
  "reduced milk",
  "Lemon juice",
  "coconut flakes",
  "Condensed milk",
  "fried milk power",
  "sugar syrup",
  "Besan",
  "Milk",
  "jaggery",
  "Loaf bread",
  "salt",
  "Black lentils",
  "mung bean",
  "desiccated coconut",
  "Jowar flour",
  "Bombay duck",
  "malvani masala",
  "bombay rava",
  "Citric acid",
  "chana daal",
  "nestle cream",
  "coconut ice",
  "Whole wheat rava",
  "chia seed",
  "edible gum",
  "litre milk",
  "Green chilies",
  "rapeseed oil",
  "Mango",
  "low fat",
  "Green chili paste",
  "white sesame seeds",
  "Turmeric",
  "Cinnamon",
  "Rose syrup",
  "falooda sev",
  "mixed nuts",
  "Bottle gourd",
  "Green",
  "sauce",
  "sliced almonds",
  "Dry fruits",
  "all purpose flour",
  "Whole wheat flour",
  "honey",
  "butter",
  "garlic",
  "Green beans",
  "khus khus",
  "low fat",
  "Paneer",
  "whipping cream",
  "tandoori masala",
  "bell pepper",
  "Kala chana",
  "mashed potato",
  "boondi",
  "sev",
  "Musk melon seeds",
  "poppy seeds",
  "edible gum",
  "Urad dal",
  "sev",
  "Chopped tomatoes",
  "Arbi ke patte",
  "sesame seeds",
  "gur",
  "bengal gram flour",
  "imli",
  "Fennel",
  "tea bags",
  "Kasuri methi",
  "Red kidney beans",
  "mustard oil",
  "Potatoes",
  "Green peas",
  "Sattu",
  "atta",
  "dough",
  "filling",
  "Cottage cheese",
  "malai",
  "Rose water",
  "white bread slices",
  "Badam",
  "Baby corn",
  "french beans",
  "Greek yogurt",
  "marinade",
  "Chickpea flour",
  "biryani masala powder",
  "fish fillets",
  "green bell pepper",
  "Whole wheat flour",
  "arhar dal",
  "Kala jeera",
  "Raw banana",
  "elephant foot yam",
  "long beans",
  "tindora",
  "Split pigeon peas",
  "fresh coconut",
  "Sesame oil",
  "Lentils",
  "black pepper",
  "Raw rice",
  "Axone",
  "Potol",
  "Tomato",
  "Chillies",
  "Ginger",
  "Garlic",
  "Boiled pork",
  "Onions",
  "Cauliflower",
  "Potato",
  "Garam masala",
  "curry leaves",
  "Peas",
  "Fenugreek leaves",
  "Shimla mirch",
  "amchur powder",
  "Ladies finger",
  "Kasuri methi",
  "Chicken thighs",
  "Basmati rice",
  "Star anise",
  "Sweet",
  "Whole wheat bread",
  "Whole egg",
  "Bay leaf",
  "Cinnamon stick",
  "Moong dal",
  "Masoor dal",
  "Almond",
  "Green chilli",
  "Red onion",
  "Pigeon peas",
  "Baby potatoes",
  "Beaten rice flakes",
  "Green chilies",
  "Lemon juice",
  "Gravy",
  "Bitter gourd",
  "Tea leaves",
  "Eggs",
  "Beetroot",
  "Maida",
  "Vegetable oil",
  "Fish",
  "Potatoes",
  "Mustard oil",
  "Green chillies",
  "Ridge gourd",
  "Brinjal",
  "Onions",
  "Salt",
  "Coriander",
  "Forbidden black rice",
  "Olive oil",
  "Slivered almonds",
  "Garlic powder",
  "Biryani masala",
  "Mixed vegetables",
  "Yellow moong daal",
  "Brown rice",
  "Soy sauce",
  "Lobster",
  "Red pepper",
  "Watercress",
  "Glutinous rice",
  "Egg yolks",
  "Dry dates",
  "Dried rose petals",
  "Arrowroot powder",
  "Fennel seeds",
  "Ginger powder",
  "Fresh green peas",
  "Yellow mustard",
  "Black salt",
  "Drumstick",
  "Tamarind paste",
  "Sambar powder",
  "Spinach",
  "Greens",
  "Fenugreek seeds",
  "Amaranth leaves",
  "Beef",
  "Green chilies",
  "Chole",
  "Bhatura",
  "Maida flour",
  "Corn flour",
  "Baking soda",
  "Vinegar",
  "Curd",
  "Rice flour",
  "Jaggery",
  "Cashews and raisins",
  "Jaggery syrup",
  "Peanuts",
  "Dharwadi buffalo milk",
  "Milk powder",
  "Dry fruits",
  "Arrowroot powder",
  "Tea leaves",
  "Fennel",
  "Tomatoes",
  "Cilantro",
  "Fenugreek leaves",
  "Badam",
  "Papaya",
  "Panch phoran masala",
  "Nigella seeds",
  "Tamarind",
  "Pearl onions",
  "Drumsticks",
  "Sevai",
  "Parboiled rice",
  "Steamer",
  "Curd",
  "Lentils",
  "Black pepper",
  "Vegetable oil",
  "Curry leaves",
  "Mustard seeds",
  "Mustard",
  "Chickpeas",
  "Tomato paste",
  "Avocado oil",
  "Mustard seeds",
  "Aloo",
  "Pomegranate",
  "Star anise",
  "Dates",
  "Green garlic chutney",
  "Fresh green peas",
  "Plain flour",
  "Red chillies",
  "Raw peanuts",
  "Sabudana",
  "Avocado oil",
  "Khaman",
  "Powdered sugar",
  "Black pepper",
  "Sunflower oil",
  "Gur",
  "Rice flakes",
  "Sticky rice",
  "Orange rind",
  "Raw papaya",
  "Tea bags",
  "Basmati rice",
  "Cardamom pods",
  "Green beans",
  "Bitter gourd",
  "Ridge gourd",
  "Banana",
  "Brinjal",
  "Glutinous rice",
  "Black sesame seeds",
  "Gur",
  "Egg yolks",
  "All purpose flour",
  "Dry dates",
  "Dried rose petals",
  "Pistachio",
  "Arrowroot powder",
  "Brown rice",
  "Black pepper",
  "Ginger powder",
  "Jowar flour",
  "Sesame seeds",
  "Malvani masala",
  "Bombay rava",
  "Citric acid",
  "Dried mango",
  "Nestle cream",
  "Coconut ice",
  "Dal",
  "Kokum",
  "Pav",
  "Aloo",
  "Peanut",
  "Pomegranate",
  "Bhuna chana",
  "Masalas",
  "Sattu",
  "Pav bhaji masala",
  "Gobi",
  "Dinner rolls",
  "Raw peanuts",
  "Sabudana",
  "Powdered sugar",
  "Black pepper",
  "Sunflower oil",
  "Basil",
  "Milk powder",
  "Jaggery",
  "Cashew nuts",
  "Rapeseed oil",
  "Honey",
  "Butter",
  "Garlic",
  "Fenugreek leaves",
  "Lemon",
  "Tomatoes",
  "Butter",
  "Water",
  "Fresh coconut",
  "Tea leaves",
  "Fenugreek seeds",
  "Lamb",
  "Cud",
  "Turmeric",
  "Bay leaf",
  "Prawns",
  "Mustard seed",
  "Saffron",
  "Tomato sauce",
  "Skinless chicken breasts",
  "Heavy cream",
  "Star anise",
  "Sweet green chillies",
  "Greek yogurt",
  "Cream",
  "Chickpea flour",
  "Biryani masala powder",
  "Fish fillets",
  "Green bell pepper",
  "Kala jeera",
  "Raw banana",
  "Elephant foot yam",
  "Long beans",
  "Tindora",
  "Split pigeon peas",
  "Fresh coconut",
  "Sesame oil",
  "Lentils",
  "Black pepper",
  "Raw rice",
  "Axone",
  "Potol",
  "Tomato",
  "Chillies",
  "Ginger",
  "Garlic",
  "Boiled pork",
  "Onions",
  "Cauliflower",
  "Potato",
  "Garam masala",
  "Curry leaves",
  "Peas",
  "Fenugreek leaves",
  "Shimla mirch",
  "Amchur powder",
  "Ladies finger",
  "Kasuri methi",
  "Chicken thighs",
  "Basmati rice",
  "Star anise",
  "Sweet",
  "Whole wheat bread",
  "Whole egg",
  "Bay leaf",
  "Cinnamon stick",
  "Moong dal",
  "Masoor dal",
  "Almond",
  "Green chilli",
  "Red onion",
  "Pigeon peas",
  "Baby potatoes",
  "Beaten rice flakes",
  "Green chilies",
  "Lemon juice",
  "Gravy",
  "Bitter gourd",
  "Tea leaves",
  "Eggs",
  "Beetroot",
  "Maida",
  "Vegetable oil",
  "Fish",
  "Potatoes",
  "Mustard oil",
  "Green chillies",
  "Ridge gourd",
  "Brinjal",
  "Onions",
  "Salt",
  "Coriander",
  "Forbidden black rice",
  "Olive oil",
  "Slivered almonds",
  "Garlic powder",
  "Biryani masala",
  "Mixed vegetables",
  "Yellow moong daal",
  "Brown rice",
  "Soy sauce",
  "Lobster",
  "Red pepper",
  "Watercress",
  "Glutinous rice",
  "Egg yolks",
  "Dry dates",
  "Dried rose petals",
  "Arrowroot powder",
  "Fennel seeds",
  "Ginger powder",
  "Fresh green peas",
  "Yellow mustard",
  "Black salt",
  "Drumstick",
  "Tamarind paste",
  "Sambar powder",
  "Spinach",
  "Greens",
  "Fenugreek seeds",
  "Amaranth leaves",
  "Beef",
  "Green chilies",
  "Chole",
  "Bhatura",
  "Maida flour",
  "Corn flour",
  "Baking soda",
  "Vinegar",
  "Curd",
  "Rice flour",
  "Jaggery",
  "Cashews and raisins",
  "Jaggery syrup",
  "Peanuts",
  "Dharwadi buffalo milk",
  "Milk powder",
  "Dry fruits",
  "Arrowroot powder",
  "Tea leaves",
  "Fennel",
  "Tomatoes",
  "Cilantro",
  "Fenugreek leaves",
  "Badam",
  "Papaya",
  "Panch phoran masala",
  "Nigella seeds",
  "Tamarind",
  "Pearl onions",
  "Drumsticks",
  "Sevai",
  "Parboiled rice",
  "Steamer",
  "Curd",
  "Lentils",
  "Black pepper",
  "Vegetable oil",
  "Curry leaves",
  "Mustard seeds",
  "Mustard",
  "Chickpeas",
  "Tomato paste",
  "Avocado oil",
  "Mustard seeds",
  "Aloo",
  "Pomegranate",
  "Star anise",
  "Dates",
  "Green garlic chutney",
  "Fresh green peas",
  "Plain flour",
  "Red chillies",
  "Raw peanuts",
  "Sabudana",
  "Avocado oil",
  "Khaman",
  "Powdered sugar",
  "Black pepper",
  "Sunflower oil",
  "Gur",
  "Rice flakes",
  "Sticky rice",
  "Orange rind",
  "Raw papaya",
  "Tea bags",
  "Basmati rice",
  "Cardamom pods",
  "Green beans",
  "Bitter gourd",
  "Ridge gourd",
  "Banana",
  "Brinjal",
];
